# Build Stage
ARG NODE_IMAGE="16.18.1-alpine3.16"
ARG NODE_ENV="production"
FROM node:${NODE_IMAGE} as build-stage
ENV APP_HOME="/app"
RUN mkdir -p $APP_HOME
COPY . $APP_HOME
RUN cd $APP_HOME && npm install \
  --prefer-offline \
  --pure-lockfile \
  --non-interactive \
  --production=true
WORKDIR $APP_HOME
RUN npm run build
RUN npx browserslist@latest --update-db
RUN npm run generate
# Production Stage
FROM nginx:stable-alpine as production-stage
ENV APP_HOME="/app"
COPY --from=build-stage $APP_HOME/dist /usr/share/nginx/html
RUN chown -R nginx:nginx /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]