# Build Stage
ARG NODE_ENV="production"
ARG NODE_IMAGE="16.18.1-alpine3.16"

FROM node:${NODE_IMAGE} as builder

RUN apk add --no-cache \
        python3 \
        py3-pip \
        tree \
    && pip3 install --upgrade pip \
    && pip3 install --no-cache-dir \
        awscli \
    && rm -rf /var/cache/apk/*

RUN aws --version   # Just to make sure its installed alright

WORKDIR /app
COPY ./ /app
RUN npm install
RUN npm run build
EXPOSE 3000
ENV HOST 0.0.0.0
ENV NUXT_PORT=3000

#RUN npx browserslist@latest --update-db

#RUN npm install caniuse-lite

# For Dev run this command CMD [ "npm", "run", "dev" ]
# For Prod run this command
ENTRYPOINT [ "npm", "run", "start" ]