# THIS IMAGE IS NOT USED IN PRODUCTION ONLY FOR LOCAL TESTING DinD
FROM alpine:3.17

ENV AWS_ACCESS_KEY_ID=""
ENV AWS_SECRET_ACCESS_KEY=""
ENV AWS_DEFAULT_REGION=""
ENV AWS_PROFILE=""
ENV PROJECT_ID=""
ENV AWS_REGION_NAME=""

ARG PROJECT_ID=""
ARG EC2_SSH_PUBLIC_KEY=""

ARG AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ARG AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
ARG AWS_PROFILE=$AWS_PROFILE
ARG EC2_INSTANCE_TYPE="t2.nano"
ARG EC2_INSTANCE_COUNT_PER_AZ="1"
ARG AWS_REGION_NAME=""
ARG KUBECONFIG=""
ARG KUBE_CONFIG_DATA=""

ENV POP_NAME="syn-pop"
ENV CLOUD_PROVIDER="aws"
ENV restapi_method="create"
ENV EC2_INSTANCE_TYPE="t2.nano"
ENV EC2_INSTANCE_COUNT_PER_AZ="1"
ENV KUBECONFIG=""
ENV KUBE_CONFIG_DATA=""

RUN apk update
RUN apk add --no-cache openrc openssl openssh-keygen bash curl wget aws-cli git terraform ansible tree docker
#RUN aok add docker
# RUN apk add openssh-client
# RUN rc-update add docker boot
# RUN addgroup username docker
# RUN service docker start
# RUN sleep 120

# Install kubectl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin

ENV BASE_URL="https://storage.googleapis.com/kubernetes-helm"

RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh

RUN mkdir ~/.aws
RUN echo "[default]" >> ~/.aws/credentials
RUN echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
RUN echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
RUN echo "region=eu-west-2" >> ~/.aws/credentials
RUN echo "output=json" >> ~/.aws/credentials

RUN mkdir -p ~/.ssh
RUN mkdir -p /root/.ssh

WORKDIR /

COPY . .

RUN ls -la ~/.aws
RUN tree ~/.aws

ENTRYPOINT ["bash", "devops/docker/kickstart_runner.sh"]