apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nebuladns.fullname" . }}-config
  labels:
    {{- include "nebuladns.labels" . | nindent 4 }}
data:
  nebuladns.toml: |
{{ .Values.config | indent 4 }}
{{- range .Values.zones }}

    [[zones]]
    file = "/etc/nebuladns/zones/{{ .name }}.toml"
{{- end }}
{{- if .Values.zones }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nebuladns.fullname" . }}-zones
  labels:
    {{- include "nebuladns.labels" . | nindent 4 }}
data:
{{- range .Values.zones }}
  {{ .name }}.toml: |
{{ .content | indent 4 }}
{{- end }}
{{- end }}
