# .github/workflows/deploy.yml
name: CD - Helm 1-Click Deploy OdinCM to an ENV - to Kubernetes

on:
  push:
    branches: [ dummy ]
  pull_request:
    branches: [ dummy/* ]
  workflow_dispatch:
    inputs:
      ENV_REF:
        type: choice
        description: 'Please choose the Target Environment'
        default: 'test'
        required: true
        options:
        - test
        - acc
        - prod

      TARGET_CLUSTER:      
        type: choice
        description: 'Please choose the Target K3S Cluster(s)'
        default: 'k3s2'
        required: true
        options:
        - k3s1
        - k3s2
        - k3s3
        - All

      cmd_action:
        type: choice
        description: 'Please choose the GH Action'
        default: 'update'
        required: true
        options:
        - install
        - uninstall
        - Choose

      AWS_REGION_NAME:
        type: choice
        description: 'Please choose the AWS Region name, only pplication while create'
        default: 'london'
        required: true
        options:
        - london
        - dublin
        - Choose

      k3s_cluster_name:
        type: choice
        description: 'Please choose the k3s cluster name'
        default: 'k3s2'
        required: true
        options:
        - k3s1
        - k3s2
        - Choose

env:
  TARGET_ENV: ${{ github.event.inputs.ENV_REF }}
  TARGET_CLUSTER: ${{ github.event.inputs.TARGET_CLUSTER }}
  AWS_ACCOUNT_NO: ${{ secrets.AWS_ACCOUNT_NO }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  AWS_REGION_NAME: ${{ github.event.inputs.AWS_REGION_NAME }}
  cmd_action: ${{ github.event.inputs.cmd_action }}
  REPLICA_COUNT: "1"
  POP_UPDATE_TYPE: ${{ github.event.inputs.pop_update_type }}

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - TEST_NAME: "Specific v2"
            AWS_CLI_VERSION: "2.11.6"
          - TEST_NAME: "No Input"

    name: Test ${{ matrix.TEST_NAME }} ${{ matrix.AWS_CLI_VERSION }}
    steps:
      - name: Test ${{ matrix.TEST_NAME }}
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: ${{ matrix.AWS_CLI_VERSION }}
      - run: |
          aws --version
          aws sts get-caller-identity 
        shell: bash

