name: 'Docker Image matrix - Creates a new Docker images and tags them'
run-name: 'Docker Image matrix - Creates a new Docker images and tags them'

# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-links:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Test run bash
        run: ls -al && tree

      - name: Test if docker is available
        run: docker -v
        
        
      