name: Build odincm docker image and Deploy to Kubernetes

on:
  push:
    branches: [ dummy ]
  pull_request:
    branches: [ dummy/* ]
  workflow_dispatch:
    inputs:
      ENV_REF:
        type: choice
        description: 'Please choose the Target Environment'
        default: 'test'
        required: true
        options:
        - test
        - acc
        - prod

      TARGET_CLUSTER:      
        type: choice
        description: 'Please choose the Target K3S Cluster(s)'
        default: 'k3s2'
        required: true
        options:
        - k3s1
        - k3s2
        - k3s3
        - All

      cmd_action:
        type: choice
        description: 'Please choose the GH Action'
        default: 'update'
        required: true
        options:
        - install
        - uninstall
        - Choose

      AWS_REGION_NAME:
        type: choice
        description: 'Please choose the AWS Region name, only pplication while create'
        default: 'london'
        required: true
        options:
        - london
        - dublin
        - Choose

      k3s_cluster_name:
        type: choice
        description: 'Please choose the k3s cluster name'
        default: 'k3s2'
        required: true
        options:
        - k3s1
        - k3s2
        - Choose

env:
  TARGET_ENV: ${{ github.event.inputs.ENV_REF }}
  TARGET_CLUSTER: ${{ github.event.inputs.TARGET_CLUSTER }}
  AWS_ACCOUNT_NO: ${{ secrets.AWS_ACCOUNT_NO }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  AWS_REGION_NAME: ${{ github.event.inputs.AWS_REGION_NAME }}

  cmd_action: ${{ github.event.inputs.cmd_action }}
  REPLICA_COUNT: "1"
  POP_UPDATE_TYPE: ${{ github.event.inputs.pop_update_type }}
#  KUBE_CONFIG_DATA_K3S2: ${{ secrets.KUBE_CONFIG_DATA_K3S2 }}
  
jobs:
  # *** This workflow contains a single job called "build" ***
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install or Uninstall Odincm frontend
        run: |
          echo "KUBE_CONFIG_DATA=${{ secrets.KUBE_CONFIG_DATA_K3S2 }}" >> $GITHUB_ENV
          chmod +x ./workflow_runner.sh && ./workflow_runner.sh "${{ env.cmd_action }}" "${{ env.REPLICA_COUNT }}" "${{ env.AWS_REGION_NAME }}" "${{ env.AWS_ACCOUNT_NO }}" "${{ secrets.AWS_ACCESS_KEY_ID }}" "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          # "update" "1" "eu-west-2" "KUBECONFIGPATH" "" "" ""
        shell: bash

    - name: Helm Deploy - Release to selected K3S cluster
      uses: koslib/helm-eks-action@master
      with:
        command: |
          helm upgrade -i wsl-${{ env.TARGET_ENV }} ./devops/odincm-chart -f devops/odincm-chart/values-${{ env.TARGET_ENV }}-${{ env.TARGET_CLUSTER}}.yaml --set-string targetImage="${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}" --set-string targetImageTag="${{ env.IMAGE_TAG }}" --namespace ${{ env.TARGET_ENV }} --create-namespace
          kubectl rollout restart deployment/wsl-${{ env.TARGET_ENV }} -n ${{ env.TARGET_ENV }}
          kubectl rollout history deployment/wsl-${{ env.TARGET_ENV }} -n ${{ env.TARGET_ENV }}

      - name: Slack Notification for Odincm Frontend release 
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

